export const sampleQuestionsSeed = [
  {
    category: "mern-stack",
    question: "Explain the MERN stack and how each component interacts in a typical application.",
    expectedAnswer: "MongoDB stores data, Express handles routing/middleware, React renders UI, Node.js runs the server.",
    keyPoints: ["MongoDB", "Express", "React", "Node.js", "REST API"],
    followUpQuestions: ["How would you structure a MERN monorepo?"],
    difficulty: "easy" as const,
    type: "technical" as const,
  },
  {
    category: "frontend",
    question: "What is the Virtual DOM in React and why is it useful?",
    expectedAnswer: "A lightweight copy of the real DOM used to compute minimal updates before applying changes to the actual DOM.",
    keyPoints: ["Reconciliation", "Performance", "Diffing algorithm"],
    followUpQuestions: ["When might the Virtual DOM not help performance?"],
    difficulty: "medium" as const,
    type: "technical" as const,
  },
  {
    category: "backend",
    question: "How would you design authentication for a REST API?",
    expectedAnswer: "Use JWT or session tokens, HTTPS, secure password hashing, refresh tokens, and rate limiting.",
    keyPoints: ["JWT", "bcrypt", "HTTPS", "refresh tokens"],
    followUpQuestions: ["How do you handle token revocation?"],
    difficulty: "medium" as const,
    type: "technical" as const,
  },
  {
    category: "java",
    question: "Explain the difference between ArrayList and LinkedList in Java.",
    expectedAnswer: "ArrayList uses dynamic array with O(1) random access; LinkedList uses nodes with O(1) insert/delete at ends.",
    keyPoints: ["Time complexity", "Memory layout", "Use cases"],
    followUpQuestions: ["When would you prefer LinkedList?"],
    difficulty: "easy" as const,
    type: "technical" as const,
  },
  {
    category: "python",
    question: "What are Python decorators and give a practical example?",
    expectedAnswer: "Functions that wrap other functions to extend behavior without modifying them, e.g. @login_required.",
    keyPoints: ["Higher-order functions", "Syntax", "Use cases"],
    followUpQuestions: ["How do functools.wraps help?"],
    difficulty: "medium" as const,
    type: "technical" as const,
  },
  {
    category: "data-structures",
    question: "Explain time complexity of binary search and when it applies.",
    expectedAnswer: "O(log n) on sorted arrays by halving the search space each step.",
    keyPoints: ["Sorted input", "Divide and conquer", "O(log n)"],
    followUpQuestions: ["Implement binary search iteratively."],
    difficulty: "easy" as const,
    type: "technical" as const,
  },
  {
    category: "hr",
    question: "Tell me about a time you handled conflict in a team.",
    expectedAnswer: "STAR format: Situation, Task, Action, Result with emphasis on communication and resolution.",
    keyPoints: ["STAR method", "Communication", "Outcome"],
    followUpQuestions: ["What would you do differently?"],
    difficulty: "easy" as const,
    type: "hr" as const,
  },
  {
    category: "system-design",
    question: "How would you design a URL shortener like bit.ly?",
    expectedAnswer: "Hash generation, key-value store, redirect service, analytics, rate limiting, custom domains.",
    keyPoints: ["Base62 encoding", "Database choice", "Scalability", "Caching"],
    followUpQuestions: ["How do you handle hash collisions?"],
    difficulty: "hard" as const,
    type: "technical" as const,
  },
];
